### ISSUE TITLE
Is support with Geyser-Standalone？

### ISSUE THREAD

**Issue by obtar** [Camotoy/GeyserSkinManager#31]
In server, we using Geyser-Standalone + GeyserConnect to proxy multiple JAVA servers. Servers online-mode is all turn on.
It's compatible with Geyser-Standalone?  and Bedrock skins visible on servers.

**Comment by Camotoy** [comment]
If Java Edition online mode is enabled, then each account's Java skin should already be used?

**Comment by obtar** [comment]
Yes, Bedrock player login Microsoft account. They skins will be force change displayed minecraft.net skins. 

Is it normal? How can I fix this? 
thank you.
