### ISSUE TITLE
Problem when transferring between server's on bungee

### ISSUE THREAD

**Issue by Hellohi3654** [Camotoy/GeyserSkinManager#6]
There seems to be a problem where a bedrock player's skin is removed when transferring servers on bungeecord
The bedrock player still sees their skin but java players see Steve or Alex

**Comment by LegendaryBob13** [comment]
I'm getting the same issue. Not a big deal but would like to point it out 😄 https://hatebin.com/ujobdgcoid <-- Getting this on the spigot server. Everything on the bungee side seems to be working fine. It only messes up skins some of the time and is usually really good.

**Comment by Hellohi3654** [comment]
seems to be mostly fixed now
