### ISSUE TITLE
Not showing up

### ISSUE THREAD

**Issue by GidationBoy** [Camotoy/GeyserSkinManager#9]
So I installed the plugin on my spigot server (Not using bungeecord) and when I logged my bedrock device using floodgate and viewed the player skin from my Java account, it came up as the alex/steve default skin. 

I don't know if I missed something.

**Comment by Camotoy** [comment]
Please send a log file.

**Comment by GidationBoy** [comment]
> Please send a log file.

Where do I find that?

**Comment by Camotoy** [comment]
This is the latest.log file in your `logs` folder in your server. Use https://mclo.gs/ to keep your IPs private.

**Comment by GidationBoy** [comment]
ok

**Comment by GidationBoy** [comment]
Ok I did it do I send you the link?

**Comment by Camotoy** [comment]
Yes.

**Comment by GidationBoy** [comment]
One sec

**Comment by GidationBoy** [comment]
https://mclo.gs/Nx8KZ5Y

**Comment by GidationBoy** [comment]
Did that help?

**Comment by GidationBoy** [comment]
Ok so the bedrock skins finally showed up! I think it may have been me.
